- name: Install epel yum repository
  yum:
    name: epel-release
    state: present
  when:
    - ansible_hostname == "kvm"
  tags: [epel_install]

- name: Add opennebula Repository
  yum_repository:
        name: opennebula
        description: opennebula
        baseurl: https://downloads.opennebula.io/repo/6.2.0/CentOS/7/x86_64/
        gpgcheck: yes
        enabled: yes
        gpgkey: https://downloads.opennebula.org/repo/repo.key
  when:
    - ansible_hostname == "kvm"
  tags: [opennebula_install]


- name: install required dependencies
  yum: 
    name: "{{ item }}" 
    state: installed
  with_items:
    - qemu-kvm
    - qemu-img
    - virt-manager
    - libvirt
    - libvirt-python
    - libvirt-client
    - virt-install
    - virt-viewer
    - bridge-utils
    - sshpass
  tags: [install_dependencies]

- name: Enable and start kvm services
  service:
      name: "{{ item }}"
      state: started
      enabled: yes
  with_items:
    - libvirtd
  tags: [start_enable_kvm]


- name: Install libselinux-python (required by ansible to manage selinux)
  yum:
    name: libselinux-python
    state: present
  when:
    - ansible_hostname == "kvm"
  tags: [disable_selinux]

- name: disable selinux
  selinux:
     state: disabled
  when:
    - ansible_hostname == "kvm"
  tags: [disable_selinux]

- name: install required dependencies
  yum:
    name: opennebula-node-kvm
    state: installed
  when:
    - ansible_hostname == "kvm"
  tags: [install_dependencies]

- name: Set Password to oneadmin in master
  user:
    name: oneadmin
    password: "{{oneadmin_hash_password}}"
    shell: /bin/bash
    groups: root
  become: yes
  become_method: sudo
  when:
     - ansible_hostname == "openmaster"
  tags: [Set_password_to_oneadmin]

- name: Set Password to oneadmin in kvm
  user:
    name: oneadmin
    password: "{{oneadmin_hash_password}}"
    shell: /bin/bash
    groups: root
  become: yes
  become_method: sudo
  when:
     - ansible_hostname == "kvm"
  tags: [Set_password_to_oneadmin]

- name: Create ssh-keyscan
  command: su oneadmin -l -c 'ssh-keyscan openmaster kvm >> /var/lib/one/.ssh/known_hosts'
  become_exe: sudo
  when:
     - ansible_hostname == "openmaster"
  tags: [passwordless_ssh]

- name: Send to kvm server
  command: su oneadmin -l -c 'sshpass -p "{{oneadmin_user_password}}" ssh-copy-id oneadmin@kvm'
  when:
     - ansible_hostname == "openmaster"
  tags: [passwordless_ssh]

- name: Adding KVM Host
  command: su oneadmin -l -c 'onehost create kvm -i kvm -v kvm'
  become_exe: sudo
  when:
     - ansible_hostname == "openmaster"
  tags: [Add_KVM_Host]
