- name: Stop Opennebula Service
  service:
      name: "{{ item }}"
      state: stopped
  with_items:
    - opennebula
    - opennebula-sunstone
  when:
    - ansible_hostname == "openmaster"
  tags: [Stop_Opennebula_Service]


- name: Set SERVER_ID  on oned
  replace:
    dest: /etc/one/oned.conf
    regexp: 'SERVER_ID\s.*,'
    replace: 'SERVER_ID     = 0,'
  when:
    - ansible_hostname == "openmaster"
  tags: [Set_SERVER_ID_openmaster]

- name: Start Opennebula Service
  service:
      name: "{{ item }}"
      state: started
  with_items:
    - opennebula
    - opennebula-sunstone
  when:
    - ansible_hostname == "openmaster"
  tags: [Start_Opennebula_Service]

- name: Backup onedb backup
  shell: "{{item}}"
  with_items:
    - onedb backup -u oneadmin -p "{{opennebula_user_mysql_password}}" -d opennebula
    - sshpass -p "{{os_root_pass}}" scp -oStrictHostKeyChecking=no /var/lib/one/mysql_localhost_opennebula_*.sql openslave:/tmp
    - sshpass -p "{{os_root_pass}}" ssh openslave rm -rf /var/lib/one/.one
    - sshpass -p "{{os_root_pass}}" scp -r /var/lib/one/.one/ openslave:/var/lib/one/
  when:
    - ansible_hostname == "openmaster"
  tags: [Backup_oned_database]

- name: chown .one directory
  shell: chown -R oneadmin. /var/lib/one/.one
  when:
    - ansible_hostname == "openslave"
  tags: [chown_.one]


- name: Stop Opennebula Service on openslave
  service:
      name: "{{ item }}"
      state: stopped
  with_items:
    - opennebula
    - opennebula-sunstone
  when:
    - ansible_hostname == "openslave"
  tags: [Stop_Opennebulaslave_Service]

- name: Restore onedb backup
  shell: onedb restore -f -u oneadmin -p "{{opennebula_user_mysql_password}}" -d opennebula /tmp/mysql_localhost_opennebula_*.sql
  when:
    - ansible_hostname == "openslave"
  tags: [Restore_onedb_openslave]

- name: Set SERVER_ID  on oned on openslave
  replace:
    dest: /etc/one/oned.conf
    regexp: 'SERVER_ID\s.*,'
    replace: 'SERVER_ID     = 1,'
  when:
    - ansible_hostname == "openslave"
  tags: [Set_SERVER_ID_openslave]

- name: Start Opennebula Service openslave
  service:
      name: "{{ item }}"
      state: started
  with_items:
    - opennebula
    - opennebula-sunstone
  when:
    - ansible_hostname == "openslave"
  tags: [Start_Opennebulaslave_Service]


- name: Add port to firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - 2633/tcp
  when:
    - ansible_hostname == "openmaster"
  tags: [addport_to_firewalld]

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
  when:
    - ansible_hostname == "openmaster"
  tags: [reload_firewalld]


- name: Add port to firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - 2633/tcp
  when:
    - ansible_hostname == "openslave"
  tags: [addport_to_firewalld]

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
  when:
    - ansible_hostname == "openslave"
  tags: [reload_firewalld]


- name: Add Master to Zone
  command: onezone server-add 0 --name openmaster --rpc http://openmaster:2633/RPC2
  when:
    - ansible_hostname == "openmaster"
  tags: [Add_Master_To_Zone]

 
- name: Add Slave to Zone
  command: onezone server-add 0 --name openslave --rpc http://openslave:2633/RPC2
  when:
    - ansible_hostname == "openmaster"
  tags: [Add_Slave_To_Zone]

