- name: Stop Opennebula Service
  service:
      name: "{{ item }}"
      state: stopped
  with_items:
    - opennebula
    - opennebula-sunstone
  when:
    - ansible_hostname == "openmaster"
  tags: [Stop_Opennebula_Service]


- name: Set SERVER_ID  on oned
  replace:
    dest: /etc/one/oned.conf
    regexp: 'SERVER_ID'
    replace: 'SERVER_ID = 0 ,'
  when:
    - ansible_hostname == "openmaster"
  tags: [Set_SERVER_ID]

- name: Start Opennebula Service
  service:
      name: "{{ item }}"
      state: started
  with_items:
    - opennebula
    - opennebula-sunstone
  when:
    - ansible_hostname == "openmaster"
  tags: [Start_Opennebula_Service]

- name: Backup onedb backup
  shell: "{{item}}"
  with_items:
    - onedb backup -u oneadmin -p "Aa@123" -d opennebula
    - sshpass -p "qazwsx" scp -oStrictHostKeyChecking=no /var/lib/one/mysql_localhost_opennebula_*.sql openslave:/tmp
    - sshpass -p "qazwsx" ssh openslave rm -rf /var/lib/one/.one
    - sshpass -p "qazwsx" scp -r /var/lib/one/.one/ openslave:/var/lib/one/
  when:
    - ansible_hostname == "openmaster"
  tags: [Backup_oned_database]


- name: Stop Opennebula Service on openslave
  service:
      name: "{{ item }}"
      state: stopped
  with_items:
    - opennebula
    - opennebula-sunstone
  when:
    - ansible_hostname == "openslave"
  tags: [Stop_Opennebulaslave_Service]

- name: Restore onedb backup
  shell: onedb restore -f -u oneadmin -p "Aa@123" -d opennebula /tmp/mysql_localhost_opennebula_*.sql
  when:
    - ansible_hostname == "openslave"
  tags: [Restore_onedb_openslave]

- name: Set SERVER_ID  on oned on openslave
  replace:
    dest: /etc/one/oned.conf
    regexp: 'SERVER_ID\s.*,'
    replace: 'SERVER_ID = 1,'
  when:
    - ansible_hostname == "openslave"
  tags: [Set_SERVER_ID_openslave]

- name: Start Opennebula Service openslave
  service:
      name: "{{ item }}"
      state: started
  with_items:
    - opennebula
    - opennebula-sunstone
  when:
    - ansible_hostname == "openslave"
  tags: [Start_Opennebulaslave_Service]

- name: Add slave to Master
  command: onezone server-add 0 --name openslave --rpc http://{{ipv4.address}}:2633/RPC2
  when:
    - ansible_hostname == "openslave"
  tags: [Add_slave_to_master]

